spring:
  config:
    import:
      - optional:file:.env[.properties]
      - classpath:train-template.yml

  docker:
    compose:
      lifecycle-management: start_only

  jackson:
    time-zone: Asia/Seoul

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 500
          batch_versioned_data: true
        generate_statistics: false

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

train:
  schedule:
    excel:
      filename: ${TRAIN_SCHEDULE_FILENAME}
  station-fare:
    excel:
      filename: ${STATION_FARE_FILENAME}

# Prometheus
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    tags:
      application: raillo-backend
  endpoint:
    prometheus:
      access: unrestricted
